openshift/federation-v2-operator

- Dockerfile
> Tweak make command

- Dockerfile.fork
...to get managed-e2e test green
> Add USER directive to Dockerfile

- README.md
...but mostly just try to get origin image pushed :)
> Add repository layout to README

- manifests/federation-v2/0.0.4/federation-v2.v0.0.4.clusterserviceversion.yaml
Reflecting some things I found while testing.
> Update OLM manifests

- manifests/federation/0.0.5/federation.v0.0.5.clusterserviceversion.yaml
- supported InstallModes
- updates to CRD descriptions
> Updates to Federation CSV based on community-operators feedback

- README.md
- olm-testing/Dockerfile
- olm-testing/catalog-source.yaml
- scripts/install-using-catalog-source.sh
- scripts/push-operator-registry.sh
...to support testing in CI and development-time changes without having to directly modify files
> Add tooling to support image name substitution

- README.md
- olm-testing/catalog-source.yaml
> Update developer docs in README

- Dockerfile
> Fix entrypoint in federation-controller image

- scripts/install-using-catalog-source.sh
> Remove dependency on oc binary

- manifests/federation/0.0.6/federation.v0.0.6.clusterserviceversion.yaml
- scripts/install-using-catalog-source.sh
Updates to CSV description for ns-scoped federation after https://github.com/operator-framework/community-operators/issues/169 was filed.
> Update CSV description for ns-scoped federation

- manifests/federation/0.0.6/federation.v0.0.6.clusterserviceversion.yaml
- scripts/populate-community-operators.sh
Update community operators tooling and make some MD tweaks in the CSV description for ns-scoped federation
> Community operators tooling

- upstream-manifests/federation/0.0.7/federation.v0.0.7.clusterserviceversion.yaml
Add some missing fields to CSV
> Add repository/link information to metadata

- manifests/federation/0.0.8/federation.v0.0.8.clusterserviceversion.yaml
- Update name and version to 0.0.8 to match package.yaml
- Remove unknown flag `--install-crds=false` from deployment
> [CSV] Fix federation 0.0.8 manifest for OLM

- manifests/cluster-federation/0.0.8/cluster-federation.v0.0.8.clusterserviceversion.yaml
- upstream-manifests/cluster-federation/0.0.8/cluster-federation.v0.0.8.clusterserviceversion.yaml
- upstream-manifests/federation/0.0.8/federation.v0.0.8.clusterserviceversion.yaml
Update a couple of dangling references to 0.0.7 and incorporate out-of-band changes that were made to community-operators.
> Update dangling references to 0.0.7

- upstream-manifests/federation/0.0.10/federation.v0.0.10.clusterserviceversion.yaml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1710203
> Fixed documentation for kubefedctl disable command

- upstream-manifests/federation/0.0.10/federation.v0.0.10.clusterserviceversion.yaml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1710198
> Fixed documentation for Enabling federation for new API types

- upstream-manifests/federation/0.0.10/federation.v0.0.10.clusterserviceversion.yaml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1710201
> Fixed documentation for deployment instruction

- upstream-manifests/federation/0.0.10/federation.v0.0.10.clusterserviceversion.yaml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1710193
> Fixed documentation for kubefedctl unjoin command

- upstream-manifests/federation/0.0.10/federation.v0.0.10.clusterserviceversion.yaml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1710188
> Fixed documentation for kubefedctl join commmand

- upstream-manifests/federation/0.0.10/federation.v0.0.10.clusterserviceversion.yaml
fixes https://github.com/operator-framework/community-operators/pull/359
> Adding alm-examples for passing the CI test

- upstream-manifests/federation/0.0.10/federation.v0.0.10.clusterserviceversion.yaml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1710206
> Fixed "Created At" date
